mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from person.templates import *

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="index.html"), name='index'),
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^custom/', include('person.urls')),
    url(r'^users/', include('users.urls')),

]

mysite/person/urls.py
from django.conf.urls import url
from django.views.generic.base import TemplateView

from person import views

app_name = 'person'
urlpatterns = [
    url(r'^personlist/$', views.list, name='plist'),
    url(r'^createperson/$', views.create, name='pnew'),
    url(r'^collegelist/$', views.clist, name='clist'),
    url(r'^createcollege/$', views.ccreate, name='cnew'),
    url(r'^deptlist/$', views.dlist, name='dlist'),
    url(r'^createdept/$', views.dcreate, name='dnew'),
    url(r'^booklist/$', views.blist, name='blist'),
    url(r'^createbook/$', views.bcreate, name='bnew'),
]

mysite/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^(?P<question_id>[0-9]+)/unvote/$', views.unvote, name='unvote'),
]

mysite/person/models.py
from django.db import models
from django.utils import timezone
from polls.models import Question
import datetime
from django.contrib.auth.models import AbstractUser


class Person(models.Model):
    name = models.CharField(max_length=200,blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class College(models.Model):
    collegeName = models.CharField(max_length=200)
    persons = models.OneToOneField(Person,blank=True)

    def __str__(self):
        return self.collegeName

class Department(models.Model):
    dept = models.CharField(max_length=30)
    person=models.ManyToManyField(Person,blank=True)

    def __str__(self):
        return self.dept

class Books(models.Model):
    book = models.CharField(max_length=30)
    dept = models.ForeignKey(Department,blank=True)

    def __str__(self):
        return self.book

mysite/person/views.py
from django.shortcuts import get_object_or_404, render
from django.shortcuts import *
from django.utils import timezone
from .models import Question
from django.contrib import messages
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from person.models import Person,College,Department,Books
from django.forms import ModelForm

class Form(ModelForm):
    class Meta:
        model = Person
        fields = ['name']
class CForm(ModelForm):
    class Meta:
        model = College
        fields = ['collegeName','persons']
class DForm(ModelForm):
    class Meta:
        model = Department
        fields = ['dept','person']
class BForm(ModelForm):
    class Meta:
        model = Books
        fields = ['book','dept']

def create(request, template_name='person/create.html'):
    form = Form(request.POST or None)
    if form.is_valid():
        form.save()
        messages.success(request,  'Person Created')
        return redirect('person:plist')
    return render(request, template_name, {'form': form})

def list(request, template_name='person/list.html'):
    p = Person.objects.all()
    data = {}
    data['object_list'] = p
    return render(request, template_name, data)

def ccreate(request, template_name='college/create.html'):
    cform = CForm(request.POST or None)
    if cform.is_valid():
        cform.save()
        messages.success(request, 'College Created')
        return redirect('person:clist')
    return render(request, template_name, {'form': cform})

def clist(request, template_name='college/list.html'):
    c = College.objects.all()
    data = {}
    data['object_list'] = c
    return render(request, template_name, data)

def dcreate(request, template_name='dept/create.html'):
    dform = DForm(request.POST or None)
    if dform.is_valid():
        dform.save()
        messages.success(request, 'Department Created')
        return redirect('person:dlist')
    return render(request, template_name, {'form': dform})

def dlist(request, template_name='dept/list.html'):
    d = Department.objects.all()
    data = {}
    data['object_list'] = d
    return render(request, template_name, data)

def bcreate(request, template_name='books/create.html'):
    bform = BForm(request.POST or None)
    if bform.is_valid():
        bform.save()
        messages.success(request, 'Book Created')
        return redirect('person:blist')
    return render(request, template_name, {'form': bform})

def blist(request, template_name='books/list.html'):
    b = Books.objects.all()
    data = {
    }
    data['object_list'] = b
    return render(request, template_name, data)

mysite/person/templates/person/create.html
<center>
    <form method="post">{% csrf_token %}
    {% for field in form %}
        <div class="fieldWrapper">
            {{ field.errors }}
            {{ field.label_tag }}: {{ field }}
        </div>
    {% endfor %}
    <p><input type="submit" value="SAVE" /></p>
</form></center>

mysite/person/templates/person/list.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<center>
{% include 'messages.html' %}
<a href="{% url 'person:pnew' %}"><button class="btn btn-primary">Create New Person</button></a>
<a href="{% url 'person:cnew' %}"><button class="btn btn-success">Create New College</button></a>
 <a href="{% url 'person:dnew' %}"><button class="btn btn-warning">Create New Department</button></a>
 <a href="{% url 'person:bnew' %}"><button class="btn btn-theme">Create New Book</button></a>
 <a href="{% url 'person:clist' %}"><button class="btn btn-default">Goto College List</button></a>
 <a href="{% url 'person:plist' %}"><button class="btn btn-danger">Goto Hdomepage</button></a>
</center>
 <hr>
 <hr>
 <hr>
<h3><ul>
    {% for p in object_list %}
<table>
 <thead>
    <tr>
     <th>Person NAME -- ></th>
       <td><b>{{ p.name }}</b></td>
    </tr>
</thead>
<hr>

</table>
    {% endfor %}
</ul></h3>