DJANGO-Python-CRUD/apps/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'apps.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^employee/', include('employee.urls', namespace='employee')),
    url(r'^$', 'apps.views.home'),
]

DJANGO-Python-CRUD/employee/urls.py
from django.conf.urls import patterns, url

from employee import views

urlpatterns = patterns('',
  url(r'^$', views.list, name='list'),
  url(r'^new$', views.create, name='new'),
  url(r'^edit/(?P<pk>\d+)$', views.update, name='edit'),
  url(r'^delete/(?P<pk>\d+)$', views.delete, name='delete'),
)

DJANGO-Python-CRUD/employee/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Employee(models.Model):
    name = models.CharField(max_length=20)
    uniqueid = models.IntegerField()
    age = models.IntegerField()
    language = models.CharField(max_length=20)
    department = models.CharField(max_length=20)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('employee:edit', kwargs={'pk': self.pk})

DJANGO-Python-CRUD/apps/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse

def home(request):
    html = """
    <center><h1>CRUD</h1>
    <a href="/employee/">Start</a><br>  </center>  
    """
    return HttpResponse(html)

DJANGO-Python-CRUD/employee/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm

from employee.models import Employee

class EmployeeForm(ModelForm):
    class Meta:
        model = Employee
        fields = ['name', 'uniqueid', 'age', 'language','department']

def list(request, template_name='employee/list.html'):
    emp = Employee.objects.all()
    data = {}
    data['object_list'] = emp
    return render(request, template_name, data)

def create(request, template_name='employee/form.html'):
    form = EmployeeForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('employee:list')
    return render(request, template_name, {'form':form})

def update(request, pk, template_name='employee/form.html'):
    emp= get_object_or_404(Employee, pk=pk)
    form = EmployeeForm(request.POST or None, instance=emp)
    if form.is_valid():
        form.save()
        return redirect('employee:list')
    return render(request, template_name, {'form':form})

def delete(request, pk, template_name='employee/delete.html'):
    emp= get_object_or_404(Employee, pk=pk)    
    if request.method=='POST':
        emp.delete()
        return redirect('employee:list')
    return render(request, template_name, {'object':emp})

DJANGO-Python-CRUD/employee/templates/employee/delete.html
<form method="post">{% csrf_token %}
    Delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

DJANGO-Python-CRUD/employee/templates/employee/form.html
<center><form method="post">{% csrf_token %}
    {% for field in form %}
        <div class="fieldWrapper">
            {{ field.errors }}
            {{ field.label_tag }}: {{ field }}
        </div>
    {% endfor %}
    <p><input type="submit" value="SAVE" /></p>
</form></center>

DJANGO-Python-CRUD/employee/templates/employee/list.html
<h1>Employee</h1>
<h3><ul>
    {% for emp in object_list %}
<table>
 <thead>
				<tr>
				 <th>NAME</th>
     <th>IDENTITY</th>
     <th>AGE</th>
     <th>LANGUAGE</th>
     <th>DEPARTMENT</th>
     <th>UPDATE</th>
     <th>DELETE</th>
				</tr>
</thead>
<hr>
<tbody>
	<tr>
	<td>{{ emp.name }}</td>
	<td>{{ emp.uniqueid }}</td>
	<td>{{emp.age}}</td>
	<td>{{emp.language}}</td>
	<td>{{emp.department}}</td>
	<td> <a href="{% url 'employee:edit' emp.id %}">UPDATE</a></td>
	<td> <a href="{% url 'employee:delete' emp.id %}">REMOVE</a></td>
	</tr>
</tbody> 
</table>
    {% endfor %}
</ul></h3>

<center><h2><b><a href="{% url 'employee:new' %}">Create New Employee</a></b></h2></center>